apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: tempo
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: PREFIX
              value: "/tempo"
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
